export * from "./home";
export * from "./bookings";
export * from "./rooms";
export * from "./room";
export * from "./treatments";
export * from "./treatment";
export * from "./login";
export * from "./registration";
export * from "./not-found";
